/**
 * Alexander Kashyap
 * CSCI 466
 * 11/29/21
**/

use z1926618;

CREATE TABLE ORDERS(
    ORDER_NUMBER INT AUTO_INCREMENT,
    STATUS VARCHAR(70) DEFAULT 'Processing',
    CARD_NUMBER INT NOT NULL,
    CARDHOLDER VARCHAR(70) NOT NULL,
    CVV INT NOT NULL,
    BILLING_ZIP INT NOT NULL,
    ZIP INT NOT NULL,
    STREET_ADDRESS VARCHAR(70) NOT NULL,
    CITY VARCHAR(70) NOT NULL,
    STATE VARCHAR(70) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    NOTES VARCHAR(500),

    PRIMARY KEY (ORDER_NUMBER)
);

CREATE TABLE PRODUCTS(
    PRODUCT_NAME VARCHAR(70),
    QUANTITY INT,
    PRICE DOUBLE,

    PRIMARY KEY (PRODUCT_NAME)
);

CREATE TABLE ITEMS_ORDERED(
    PRODUCT_NAME VARCHAR(70),
    ORDER_NUMBER INT,
    QUANTITY INT,

    PRIMARY KEY (PRODUCT_NAME),
    FOREIGN KEY (PRODUCT_NAME) REFERENCES PRODUCTS(PRODUCT_NAME),
    FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDERS(ORDER_NUMBER)
);


CREATE TABLE CART(
    PRODUCT_NAME VARCHAR(70),
    QUANTITY INT,
    COST DOUBLE,

    PRIMARY KEY (PRODUCT_NAME),
    FOREIGN KEY (PRODUCT_NAME) REFERENCES PRODUCTS(PRODUCT_NAME)
);
